export { default as posts } from "@/sanity/schemas/posts";
export { default as category } from "@/sanity/schemas/category";
export { default as img } from "@/sanity/schemas/img";
export { default as quote } from "@/sanity/schemas/quote";
export { default as video } from "@/sanity/schemas/video";
export { default as model } from "@/sanity/schemas/model";
export { default as experiment } from "@/sanity/schemas/experiment";
export { default as tags } from "@/sanity/schemas/tag";
export { default as spline } from "@/sanity/schemas/spline";
